export const strings = {
  systemVersion: 'v1.1.0',
  auth: {
    loginTitle: 'Masuk ke Akun Anda',
    loginDescription: 'Silakan masukkan email dan kata sandi Anda untuk masuk.',
    registerTitle: 'Daftar Akun Baru',
    registerDescription: 'Silakan isi data diri Anda untuk membuat akun baru.',
    emailLabel: 'Alamat Email',
    emailPlaceholder: 'nama@domain.com',
    nameLabel: 'Nama Lengkap',
    namePlaceholder: 'John Doe',
    passwordLabel: 'Kata Sandi',
    passwordPlaceholder: '••••••••',
    confirmPasswordLabel: 'Konfirmasi Kata Sandi',
    confirmPasswordPlaceholder: '••••••••',
    forgotPasswordLink: 'Lupa Kata Sandi?',
    dontHaveAccountText: 'Belum memiliki akun?',
    registerLinkText: 'Daftar sekarang',
    alreadyHaveAccountText: 'Sudah memiliki akun?',
    loginLinkText: 'Masuk di sini',
    submitButton: 'Masuk',
    submittingButton: 'Sedang Masuk...',
    registerButton: 'Daftar',
    registeringButton: 'Sedang Mendaftar...',
    validation: {
      emailInvalid: 'Alamat email tidak valid.',
      emailRequired: 'Email wajib diisi.',
      nameRequired: 'Nama lengkap wajib diisi.',
      nameMin: 'Nama lengkap minimal harus 2 karakter.',
      passwordMin: 'Kata sandi minimal harus 8 karakter.',
      passwordRequired: 'Kata sandi wajib diisi.',
      confirmPasswordRequired: 'Konfirmasi kata sandi wajib diisi.',
      passwordsMustMatch: 'Kata sandi tidak cocok.',
      termsRequired: 'Anda harus menyetujui Syarat dan Ketentuan.',
    },
    termsLabel: 'Saya menyetujui Syarat dan Ketentuan',
    successMessage: 'Login berhasil! Selamat datang kembali.',
    errorMessage: 'Login gagal. Silakan periksa kembali email atau kata sandi Anda.',
    successRegisterMessage: 'Pendaftaran berhasil! Akun Anda telah dibuat.',
    errorRegisterMessage: 'Pendaftaran gagal. Silakan coba lagi.',
  },
  menu: {
    dashboard: 'Dashboard',
    todo: 'Lacak Tugas',
    schedule: 'Jadwal',
    finance: 'Keuangan',
    notes: 'Catatan',
    habits: 'Rutinitas',
    focus: 'Fokus',
    comingSoon: 'Segera Hadir',
  },
};
