export const strings = {
  appName: 'PCC Client',
  systemVersion: '1.1.0',
  version: 'Versi',
  rightsReserved: 'Seluruh hak dilindungi.',
  auth: {
    loginTitle: 'Masuk ke Akun Anda',
    loginDescription: 'Silakan masukkan email dan kata sandi Anda untuk masuk.',
    registerTitle: 'Daftar Akun Baru',
    registerDescription: 'Silakan isi data diri Anda untuk membuat akun baru.',
    emailLabel: 'Alamat Email',
    emailPlaceholder: 'nama@domain.com',
    nameLabel: 'Nama Lengkap',
    namePlaceholder: 'John Doe',
    passwordLabel: 'Kata Sandi',
    passwordPlaceholder: '••••••••',
    confirmPasswordLabel: 'Konfirmasi Kata Sandi',
    confirmPasswordPlaceholder: '••••••••',
    forgotPasswordLink: 'Lupa Kata Sandi?',
    dontHaveAccountText: 'Belum memiliki akun?',
    registerLinkText: 'Daftar sekarang',
    alreadyHaveAccountText: 'Sudah memiliki akun?',
    loginLinkText: 'Masuk di sini',
    submitButton: 'Masuk',
    registerButton: 'Daftar',
    validation: {
      emailInvalid: 'Alamat email tidak valid.',
      emailRequired: 'Email wajib diisi.',
      nameRequired: 'Nama lengkap wajib diisi.',
      nameMin: 'Nama lengkap minimal harus 2 karakter.',
      passwordMin: 'Kata sandi minimal harus 8 karakter.',
      passwordRequired: 'Kata sandi wajib diisi.',
      confirmPasswordRequired: 'Konfirmasi kata sandi wajib diisi.',
      passwordsMustMatch: 'Kata sandi tidak cocok.',
      termsRequired: 'Anda harus menyetujui Syarat dan Ketentuan.',
    },
    termsLabel: 'Saya menyetujui Syarat dan Ketentuan',
    errorMessage: 'Login gagal. Silakan periksa kembali email atau kata sandi Anda.',
    errorRegisterMessage: 'Pendaftaran gagal. Silakan coba lagi.',
  },
  menu: {
    dashboard: 'Dashboard',
    todo: 'Lacak Tugas',
    schedule: 'Jadwal',
    finance: 'Keuangan',
    notes: 'Catatan',
    habits: 'Rutinitas',
    focus: 'Fokus',
    comingSoon: 'Segera Hadir',
  },
  dashboard: {
    title: 'Daily Overview',
    subtitle: 'Pantau ringkasan produktivitas harian Anda dan analisis perkembangan aktivitas mingguan.',
  },
  todo: {
    title: 'Smart To-Do',
    subtitle: 'Kelola dan lacak tugas harian Anda dengan mudah.',
    addButton: 'Tambah Tugas',
    addAriaLabel: 'Tambah Tugas Baru',
    activeTasksTitle: 'Daftar Tugas Aktif',
    activeTasksSubtitle: 'Daftar semua rencana tindakan yang perlu diselesaikan.',
    emptyStateTitle: 'Belum ada tugas terpilih',
    emptyStateSubtitle: 'Pilih filter kategori di samping atau buat tugas baru untuk memulai.',
    modalDescription: 'Formulir untuk menambahkan tugas baru.',
    modalPlaceholder: 'Konten form tambah tugas akan segera hadir di sini.',
    cancelButton: 'Batal',
    saveButton: 'Simpan',
    aside: {
      contextTitle: 'Konteks',
      priorityTitle: 'Prioritas',
      reviewTitle: 'Tinjauan Hari Ini',
      contexts: {
        college: 'Kuliah',
        work: 'Kerja',
        business: 'Usaha',
        personal: 'Personal',
      },
      priorities: {
        high: 'Tinggi',
        medium: 'Sedang',
        low: 'Rendah',
      },
      stats: {
        completed: 'Selesai',
        pending: 'Tertunda',
        completionRate: 'Tingkat Penyelesaian',
        tasksCount: '{completed} dari {total} tugas selesai',
      }
    }
  }
};

