import type { TranslationType } from "@/shared/types/translation";

export const strings: Record<'id' | 'en', TranslationType> = {
  id: {
    appName: 'PCC Client',
    systemVersion: '1.2.0',
    version: 'Versi',
    rightsReserved: 'Seluruh hak dilindungi.',
    days: 'Hari',
    times: 'Kali',
    today: 'Hari Ini',
    auth: {
      loginTitle: 'Masuk ke Akun Anda',
      loginDescription: 'Silakan masukkan email dan kata sandi Anda untuk masuk.',
      registerTitle: 'Daftar Akun Baru',
      registerDescription: 'Silakan isi data diri Anda untuk membuat akun baru.',
      emailLabel: 'Alamat Email',
      emailPlaceholder: 'nama@domain.com',
      nameLabel: 'Nama Lengkap',
      namePlaceholder: 'Tim Cook',
      passwordLabel: 'Kata Sandi',
      passwordPlaceholder: '••••••••',
      confirmPasswordLabel: 'Konfirmasi Kata Sandi',
      confirmPasswordPlaceholder: '••••••••',
      forgotPasswordLink: 'Lupa Kata Sandi?',
      dontHaveAccountText: 'Belum memiliki akun?',
      registerLinkText: 'Daftar sekarang',
      alreadyHaveAccountText: 'Sudah memiliki akun?',
      loginLinkText: 'Masuk di sini',
      submitButton: 'Masuk',
      registerButton: 'Daftar',
      termsLabel: 'Saya menyetujui Syarat dan Ketentuan',
      logoutButton: 'Keluar',
    },
    menu: {
      dashboard: 'Dashboard',
      todo: 'Lacak Tugas',
      schedule: 'Jadwal',
      finance: 'Keuangan',
      notes: 'Catatan',
      habits: 'Rutinitas',
      focus: 'Fokus',
      comingSoon: 'Segera Hadir',
    },
    dashboard: {
      title: 'Daily Overview',
      subtitle: 'Pantau ringkasan produktivitas harian Anda dan analisis perkembangan aktivitas mingguan.',
    },
    todo: {
      title: 'Smart To-Do',
      subtitle: 'Kelola dan lacak tugas harian Anda dengan mudah.',
      addButton: 'Tambah Tugas',
      addAriaLabel: 'Tambah Tugas Baru',
      activeTasksTitle: 'Daftar Tugas Aktif',
      activeTasksSubtitle: 'Daftar semua rencana tindakan yang perlu diselesaikan.',
      emptyStateTitle: 'Belum ada tugas terpilih',
      emptyStateSubtitle: 'Pilih filter kategori di samping atau buat tugas baru untuk memulai.',
      modalDescription: 'Formulir untuk menambahkan tugas baru.',
      aside: {
        contextTitle: 'Konteks',
        priorityTitle: 'Prioritas',
        contexts: {
          lecture: 'Belajar',
          work: 'Kerja',
          business: 'Usaha',
          personal: 'Personal',
        },
        priorities: {
          low: 'Rendah',
          medium: 'Sedang',
          high: 'Tinggi',
          urgent: 'Urgensi',
        },
        status: {
          todo: 'Menunggu',
          inProgress: 'Dalam Proses',
          done: 'Selesai',
          cancelled: 'Dibatalkan',
        }
      },
      form: {
        titleLabel: 'Judul',
        titlePlaceholder: 'Contoh: Kuliah Aljabar Linear',
        descriptionLabel: 'Keterangan',
        descriptionPlaceholder: 'Tambahkan deskripsi atau tautan pertemuan',
        statusLabel: 'Status',
        dueDateLabel: 'Tanggal Tenggat',
        dueTimeLabel: 'Waktu Tenggat',
        tagsLabel: 'Tag',
        tagsPlaceholder: 'Contoh: Kuliah, Tugas, Meeting',
      }
    },
    schedule: {
      title: 'Jadwal Terpadu',
      subtitle: 'Pantau dan kelola jadwal aktivitas Anda dari semua kategori secara terintegrasi.',
      form: {
        titleLabel: 'Nama Kegiatan',
        titlePlaceholder: 'Contoh: Bimbingan Skripsi',
        descriptionLabel: 'Keterangan',
        descriptionPlaceholder: 'Tambahkan deskripsi atau tautan pertemuan',
        contextLabel: 'Konteks',
        startDateLabel: 'Waktu Mulai',
        endDateLabel: 'Waktu Selesai',
        isRecurringLabel: 'Ulangi Kegiatan Ini',
        recurringDaysLabel: 'Ulangi Pada Hari',
        locationLabel: 'Lokasi',
        locationPlaceholder: 'Contoh: Zoom, Google Meet',
      },
      conflictWarningTitle: 'Bentrokan Jadwal Terdeteksi!',
      conflictWarningDesc: 'Beberapa kegiatan Anda bertabrakan di tampilan ini.',
      views: {
        month: 'Bulanan',
        week: 'Mingguan',
        day: 'Harian',
      },
      dayView: {
        eventsCountLabel: '{count} Kegiatan',
        noEvents: 'Tidak ada kegiatan untuk hari ini',
        emptyStateActionDesc: 'Klik sel kosong atau tombol Tambah Jadwal untuk membuat kegiatan baru',
        recurring: 'Berulang',
        conflictMessage: 'Bentrokan jadwal: Kegiatan ini bertabrakan dengan kegiatan lain!',
      },
      weekView: {
        noEvents: 'Tidak ada kegiatan',
        conflictBadge: 'Bentrokan',
      },
    },
    finance: {
      title: 'Pelacak Keuangan',
      subtitle: 'Kelola pemasukan, pengeluaran, anggaran, dan pantau kesehatan finansial Anda.',
      totalIncome: 'Total Pemasukan',
      totalExpense: 'Total Pengeluaran',
      netBalance: 'Saldo Bersih',
      addTransaction: 'Tambah Transaksi',
      editTransaction: 'Ubah Transaksi',
      deleteTransaction: 'Hapus Transaksi',
      deleteConfirm: 'Apakah Anda yakin ingin menghapus transaksi ini?',
      setBudget: 'Atur Anggaran',
      budgetAlert: 'Peringatan Anggaran!',
      budgetLimit: 'Batas Anggaran',
      budgetStatus: 'Status Anggaran',
      incomeTrend: 'Tren Pemasukan vs Pengeluaran (6 Bulan Terakhir)',
      expenseBreakdown: 'Rincian Pengeluaran per Kategori',
      categories: {
        salary: 'Gaji',
        business: 'Usaha',
        freelance: 'Lepas (Freelance)',
        food: 'Makanan & Minuman',
        transportation: 'Transportasi',
        subscription: 'Langganan',
        education: 'Pendidikan',
        entertainment: 'Hiburan',
        others: 'Lainnya',
      },
      form: {
        titleLabel: 'Nama Transaksi',
        titlePlaceholder: 'misal: Gaji Bulanan, Makan Siang',
        typeLabel: 'Tipe Transaksi',
        amountLabel: 'Jumlah (Rp)',
        amountPlaceholder: '0',
        categoryLabel: 'Kategori',
        dateLabel: 'Tanggal',
        descriptionLabel: 'Keterangan',
        descriptionPlaceholder: 'Catatan opsional',
      },
      validation: {
        titleRequired: 'Judul transaksi wajib diisi.',
        amountRequired: 'Jumlah transaksi harus lebih besar dari 0.',
        categoryRequired: 'Kategori wajib diisi.',
        dateRequired: 'Tanggal wajib diisi.',
      },
    },
    notes: {
      title: 'Catatan',
      subtitle: 'Tulis ide, catat tugas, dan atur pemikiran Anda dengan cepat.',
      searchPlaceholder: 'Cari catatan',
      addNote: 'Catatan Baru',
      pinned: 'Disematkan',
      otherNotes: 'Catatan Lainnya',
      emptyNotes: 'Belum ada catatan',
      emptyNotesDesc: 'Mulai dengan menambahkan catatan baru di panel samping.',
      untitledNote: 'Catatan Tanpa Judul',
      saving: 'Menyimpan',
      saved: 'Tersimpan otomatis',
      editor: {
        titlePlaceholder: 'Judul catatan',
        contentPlaceholder: 'Mulai mengetik di sini',
        attachToTask: 'Lampirkan ke Tugas',
        noTaskAttached: 'Tidak ada tugas terlampir',
        tagsLabel: 'Tag',
        tagsPlaceholder: 'Tambah tag (tekan Enter)',
        bold: 'Tebal',
        italic: 'Miring',
        heading: 'Judul',
        list: 'Daftar',
        codeBlock: 'Blok Kode',
      },
      confirmDelete: 'Apakah Anda yakin ingin menghapus catatan ini?',
    },
    habits: {
      title: 'Rutinitas',
      subtitle: 'Bangun kebiasaan baik dan pantau latihan gym harian Anda untuk hidup lebih konsisten.',
      addHabit: 'Tambah Kebiasaan',
      emptyHabits: 'Belum ada kebiasaan',
      emptyHabitsDesc: 'Mulai dengan menambahkan kebiasaan baru di atas.',
      streak: 'Hari berturut-turut',
      streakActive: 'Streak Aktif',
      streakBest: 'Streak Terbaik',
      totalCompletion: 'Total Penyelesaian',
      activeHabits: 'Kebiasaan Aktif',
      bestStreak: 'Streak Terbaik',
      totalCheckIns: 'Total Penyelesaian',
      dailyCheckIn: 'Check-in Hari Ini',
      heatmapTitle: 'Heatmap Konsistensi (90 Hari Terakhir)',
      historyDetail: 'Riwayat Penyelesaian',
      frequencyLabel: 'Frekuensi',
      daysLabel: 'Hari Target',
      frequencyDaily: 'Setiap Hari',
      frequencyCustom: 'Hari Tertentu',
      myHabbits: 'Rutinitas Saya',
      form: {
        nameLabel: 'Nama Kebiasaan',
        namePlaceholder: 'Misal: Gym, Baca 30 Menit, Minum Air',
        iconLabel: 'Pilih Ikon',
        freqLabel: 'Frekuensi Target',
        daysLabel: 'Pilih Hari Target',
        submitAdd: 'Simpan Kebiasaan',
        submitCancel: 'Batal',
      },
      confirmDelete: 'Apakah Anda yakin ingin menghapus kebiasaan ini? Semua data riwayat akan dihapus.',
    },
    focus: {
      title: 'Fokus Mode (Pomodoro)',
      subtitle: 'Tingkatkan produktivitas Anda menggunakan teknik Pomodoro dengan melacak tugas.',
      startBtn: 'Mulai Fokus',
      pauseBtn: 'Jeda',
      resumeBtn: 'Lanjutkan',
      resetBtn: 'Atur Ulang',
      customizeTimer: 'Kustomisasi Timer',
      focusDurationLabel: 'Durasi Fokus (Menit)',
      breakDurationLabel: 'Durasi Istirahat (Menit)',
      minutesUnit: 'Menit',
      activeTaskLabel: 'Pilih Tugas Aktif',
      selectTaskPlaceholder: 'Pilih tugas untuk dikerjakan',
      noTaskSelected: 'Silakan pilih tugas sebelum memulai sesi fokus.',
      dailyStatsTitle: 'Statistik Harian',
      sessionsCompleted: 'Sesi Selesai',
      totalFocusTime: 'Total Waktu Fokus',
      sessionHistoryTitle: 'Riwayat Sesi',
      noHistory: 'Belum ada sesi fokus hari ini.',
      completedAt: 'Selesai pada',
      duration: 'Durasi',
      minutesVal: '{minutes} menit',
      saveSettings: 'Simpan Pengaturan',
      cancelBtn: 'Batal',
      taskTitle: 'Tugas',
      modeFocus: 'Fokus',
      modeBreak: 'Istirahat',
      alertSessionCompleted: 'Sesi fokus selesai! Waktunya istirahat.',
      alertBreakCompleted: 'Sesi istirahat selesai! Waktunya kembali fokus.',
      addTaskPlaceholder: 'Tambah tugas baru',
      addNewTaskBtn: 'Tambah',
    }
  },
  en: {
    appName: 'PCC Client',
    systemVersion: '1.2.0',
    version: 'Version',
    rightsReserved: 'All rights reserved.',
    days: 'Days',
    times: 'Times',
    today: 'Today',
    auth: {
      loginTitle: 'Sign In to Your Account',
      loginDescription: 'Please enter your email and password to sign in.',
      registerTitle: 'Register New Account',
      registerDescription: 'Please fill in your details to create a new account.',
      emailLabel: 'Email Address',
      emailPlaceholder: 'name@domain.com',
      nameLabel: 'Full Name',
      namePlaceholder: 'John Doe',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      confirmPasswordLabel: 'Confirm Password',
      confirmPasswordPlaceholder: '••••••••',
      forgotPasswordLink: 'Forgot Password?',
      dontHaveAccountText: "Don't have an account?",
      registerLinkText: 'Register now',
      alreadyHaveAccountText: 'Already have an account?',
      loginLinkText: 'Sign in here',
      submitButton: 'Sign In',
      registerButton: 'Register',
      termsLabel: 'I agree to the Terms and Conditions',
      logoutButton: 'Logout',
    },
    menu: {
      dashboard: 'Dashboard',
      todo: 'Smart To-Do',
      schedule: 'Unified Schedule',
      finance: 'Finance Tracker',
      notes: 'Quick Notes',
      habits: 'Habit & Gym Log',
      focus: 'Focus Mode',
      comingSoon: 'Coming Soon',
    },
    dashboard: {
      title: 'Daily Overview',
      subtitle: 'Monitor your daily productivity summary and analyze weekly activity progress.',
    },
    todo: {
      title: 'Smart To-Do',
      subtitle: 'Easily manage and track your daily tasks.',
      addButton: 'Add Task',
      addAriaLabel: 'Add New Task',
      activeTasksTitle: 'Active Tasks List',
      activeTasksSubtitle: 'List of all action plans that need to be completed.',
      emptyStateTitle: 'No task selected yet',
      emptyStateSubtitle: 'Select a category filter on the side or create a new task to start.',
      modalDescription: 'Form to add a new task.',
      aside: {
        contextTitle: 'Context',
        priorityTitle: 'Priority',
        contexts: {
          lecture: 'Lecture',
          work: 'Work',
          business: 'Business',
          personal: 'Personal',
        },
        priorities: {
          low: 'Low',
          medium: 'Medium',
          high: 'High',
          urgent: "Urgent"
        },
        status: {
          todo: 'To Do',
          inProgress: 'In Progress',
          done: 'Done',
          cancelled: 'Cancelled',
        }
      },
      form: {
        titleLabel: 'Title',
        titlePlaceholder: 'e.g., Linear Algebra Class',
        descriptionLabel: 'Description',
        descriptionPlaceholder: 'Add a description or meeting link',
        statusLabel: 'Status',
        dueDateLabel: 'Due Date',
        dueTimeLabel: 'Due Time',
        tagsLabel: 'Tags',
        tagsPlaceholder: 'e.g., Class, Task, Meeting',
      }
    },
    schedule: {
      title: 'Unified Schedule',
      subtitle: 'Monitor and manage your schedules across all categories in an integrated view.',
      form: {
        titleLabel: 'Event Title',
        titlePlaceholder: 'e.g., Linear Algebra Class',
        descriptionLabel: 'Description',
        descriptionPlaceholder: 'Add a description or meeting link',
        contextLabel: 'Context',
        startDateLabel: 'Start Time',
        endDateLabel: 'End Time',
        isRecurringLabel: 'Repeat This Event',
        recurringDaysLabel: 'Repeat On',
        locationLabel: 'Location',
        locationPlaceholder: 'e.g., Zoom, Google Meet',
      },
      conflictWarningTitle: 'Schedule Conflict Detected!',
      conflictWarningDesc: 'Some of your schedules conflict in this view.',
      views: {
        month: 'Month',
        week: 'Week',
        day: 'Day',
      },
      dayView: {
        eventsCountLabel: '{count} Event(s)',
        noEvents: 'No events scheduled for this day',
        emptyStateActionDesc: 'Click a blank cell or the Add Event button to schedule one',
        recurring: 'Recurring',
        conflictMessage: 'Schedule conflict: This event overlaps with another event!',
      },
      weekView: {
        noEvents: 'No events scheduled',
        conflictBadge: 'Conflict',
      },
    },
    finance: {
      title: 'Finance Tracker',
      subtitle: 'Manage income, expenses, budgets, and monitor your financial health.',
      totalIncome: 'Total Income',
      totalExpense: 'Total Expense',
      netBalance: 'Net Balance',
      addTransaction: 'Add Transaction',
      editTransaction: 'Edit Transaction',
      deleteTransaction: 'Delete Transaction',
      deleteConfirm: 'Are you sure you want to delete this transaction?',
      setBudget: 'Set Budget',
      budgetAlert: 'Budget Alert!',
      budgetLimit: 'Budget Limit',
      budgetStatus: 'Budget Status',
      incomeTrend: 'Income vs Expense Trend (Last 6 Months)',
      expenseBreakdown: 'Expense Breakdown by Category',
      categories: {
        salary: 'Salary',
        business: 'Business',
        freelance: 'Freelance',
        food: 'Food',
        transportation: 'Transportation',
        subscription: 'Subscription',
        education: 'Education',
        entertainment: 'Entertainment',
        others: 'Others',
      },
      form: {
        titleLabel: 'Transaction Title',
        titlePlaceholder: 'e.g., Monthly Salary, Lunch',
        typeLabel: 'Transaction Type',
        amountLabel: 'Amount',
        amountPlaceholder: '0',
        categoryLabel: 'Category',
        dateLabel: 'Date',
        descriptionLabel: 'Description',
        descriptionPlaceholder: 'Optional notes',
      },
      validation: {
        titleRequired: 'Transaction title is required.',
        amountRequired: 'Amount must be greater than 0.',
        categoryRequired: 'Category is required.',
        dateRequired: 'Date is required.',
      },
    },
    notes: {
      title: 'Quick Notes',
      subtitle: 'Jot down ideas, draft lists, and capture your thoughts instantly.',
      searchPlaceholder: 'Search notes',
      addNote: 'New Note',
      pinned: 'Pinned',
      otherNotes: 'Notes',
      emptyNotes: 'No notes found',
      emptyNotesDesc: 'Start by creating a new note in the sidebar.',
      untitledNote: 'Untitled Note',
      saving: 'Saving',
      saved: 'Auto-saved',
      editor: {
        titlePlaceholder: 'Note title',
        contentPlaceholder: 'Start typing here',
        attachToTask: 'Attach to Task',
        noTaskAttached: 'No task attached',
        tagsLabel: 'Tags',
        tagsPlaceholder: 'Add tag (press Enter)',
        bold: 'Bold',
        italic: 'Italic',
        heading: 'Heading',
        list: 'List',
        codeBlock: 'Code Block',
      },
      confirmDelete: 'Are you sure you want to delete this note?',
    },
    habits: {
      title: 'Habit & Gym Log',
      subtitle: 'Build good habits and track your gym logs to maintain a consistent lifestyle.',
      addHabit: 'Add Habit',
      emptyHabits: 'No habits found',
      emptyHabitsDesc: 'Get started by creating a new habit above.',
      streak: 'days streak',
      streakActive: 'Active Streak',
      streakBest: 'Best Streak',
      totalCompletion: 'Total Completion',
      activeHabits: 'Active Habits',
      bestStreak: 'Best Streak',
      dailyCheckIn: 'Daily Check-in',
      totalCheckIns: 'Total Check-ins',
      heatmapTitle: 'Consistency Heatmap (Last 90 Days)',
      historyDetail: 'Completion History',
      frequencyLabel: 'Frequency',
      daysLabel: 'Target Days',
      frequencyDaily: 'Everyday',
      frequencyCustom: 'Specific Days',
      myHabbits: 'My Habits',
      form: {
        nameLabel: 'Habit Name',
        namePlaceholder: 'e.g. Gym, Read 30m, Drink Water',
        iconLabel: 'Choose Icon',
        freqLabel: 'Target Frequency',
        daysLabel: 'Choose Target Days',
        submitAdd: 'Save Habit',
        submitCancel: 'Cancel',
      },
      confirmDelete: 'Are you sure you want to delete this habit? All history will be lost.',
    },
    focus: {
      title: 'Focus Mode (Pomodoro)',
      subtitle: 'Boost your productivity using Pomodoro technique paired with task tracking.',
      startBtn: 'Start Focus',
      pauseBtn: 'Pause',
      resumeBtn: 'Resume',
      resetBtn: 'Reset',
      customizeTimer: 'Customize Timer',
      focusDurationLabel: 'Focus Duration (Minutes)',
      breakDurationLabel: 'Break Duration (Minutes)',
      minutesUnit: 'Minutes',
      activeTaskLabel: 'Select Active Task',
      selectTaskPlaceholder: 'Select a task to work on',
      noTaskSelected: 'Please select a task before starting a focus session.',
      dailyStatsTitle: 'Daily Statistics',
      sessionsCompleted: 'Sessions Completed',
      totalFocusTime: 'Total Focus Time',
      sessionHistoryTitle: 'Session History',
      noHistory: 'No focus sessions completed today.',
      completedAt: 'Completed at',
      duration: 'Duration',
      minutesVal: '{minutes} mins',
      saveSettings: 'Save Settings',
      cancelBtn: 'Cancel',
      taskTitle: 'Task',
      modeFocus: 'Focus',
      modeBreak: 'Break',
      alertSessionCompleted: 'Focus session completed! Time for a break.',
      alertBreakCompleted: 'Break session completed! Time to get back to focus.',
      addTaskPlaceholder: 'Add a new task',
      addNewTaskBtn: 'Add',
    }
  }
};
